ci

diff --git a/.github/workflows/commit-stage.yml b/.github/workflows/commit-stage.yml
--- a/.github/workflows/commit-stage.yml
+++ b/.github/workflows/commit-stage.yml
@@ -1,5 +1,10 @@
-name: Commit Stage
-on: push
+name: dear-comrade-topic-ci-cd
+on: 
+  push:
+    branches: [ci-cd]
+  pull_request:
+    branches: [ci-cd]
+
 
 env:
   REGISTRY: ghcr.io
@@ -8,76 +13,97 @@ env:
 
 jobs:
   build:
-    name: Build and Test
+    name: build-test
     runs-on: ubuntu-22.04
-    permissions:
-      contents: read
-      security-events: write
     steps:
-      - name: Checkout source code
+      - name: checkout-source-code
         uses: actions/checkout@v3
-      - name: Set up JDK
+
+      - name: setup-jdk
         uses: actions/setup-java@v3
         with:
           distribution: temurin
           java-version: 17
           cache: gradle
-      - name: Build, unit tests and integration tests
-        run: |
-          chmod +x gradlew
-          ./gradlew build
-      - name: Code vulnerability scanning
-        uses: anchore/scan-action@v3
-        id: scan
-        with:
-          path: "${{ github.workspace }}"
-          fail-build: false
-          severity-cutoff: high
-      - name: Upload vulnerability report
-        uses: github/codeql-action/upload-sarif@v2
-        if: success() || failure()
-        with:
-          sarif_file: ${{ steps.scan.outputs.sarif }}
-  package:
-    name: Package and Publish
-    if: ${{ github.ref == 'refs/heads/main' }}
-    needs: [ build ]
-    runs-on: ubuntu-22.04
-    permissions:
-      contents: read
-      packages: write
-      security-events: write
-    steps:
-      - name: Checkout source code
-        uses: actions/checkout@v3
-      - name: Set up JDK
-        uses: actions/setup-java@v3
-        with:
-          distribution: temurin
-          java-version: 17
-          cache: gradle
-      - name: Build container image
-        run: |
-          chmod +x gradlew
-          ./gradlew bootBuildImage \
-            --imageName ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
-      - name: OCI image vulnerability scanning
-        uses: anchore/scan-action@v3
-        id: scan
-        with:
-          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
-          fail-build: false
-          severity-cutoff: high
-      - name: Upload vulnerability report
-        uses: github/codeql-action/upload-sarif@v2
-        if: success() || failure()
-        with:
-          sarif_file: ${{ steps.scan.outputs.sarif }}
-      - name: Log into container registry
-        uses: docker/login-action@v2
-        with:
-          registry: ${{ env.REGISTRY }}
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-      - name: Publish container image
-        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
+
+      - name: grant-execution-permissions-for-gradlew
+        run: chmod +x gradlew
+        
+      - name: build-test
+        run: ./gradlew build
+
+# jobs:
+#   build:
+#     name: Build and Test
+#     runs-on: ubuntu-22.04
+#     permissions:
+#       contents: read
+#       security-events: write
+#     steps:
+#       - name: Checkout source code
+#         uses: actions/checkout@v3
+#       - name: Set up JDK
+#         uses: actions/setup-java@v3
+#         with:
+#           distribution: temurin
+#           java-version: 17
+#           cache: gradle
+#       - name: Build, unit tests and integration tests
+#         run: |
+#           chmod +x gradlew
+#           ./gradlew build
+#       - name: Code vulnerability scanning
+#         uses: anchore/scan-action@v3
+#         id: scan
+#         with:
+#           path: "${{ github.workspace }}"
+#           fail-build: false
+#           severity-cutoff: high
+#       - name: Upload vulnerability report
+#         uses: github/codeql-action/upload-sarif@v2
+#         if: success() || failure()
+#         with:
+#           sarif_file: ${{ steps.scan.outputs.sarif }}
+#   package:
+#     name: Package and Publish
+#     if: ${{ github.ref == 'refs/heads/main' }}
+#     needs: [ build ]
+#     runs-on: ubuntu-22.04
+#     permissions:
+#       contents: read
+#       packages: write
+#       security-events: write
+#     steps:
+#       - name: Checkout source code
+#         uses: actions/checkout@v3
+#       - name: Set up JDK
+#         uses: actions/setup-java@v3
+#         with:
+#           distribution: temurin
+#           java-version: 17
+#           cache: gradle
+#       - name: Build container image
+#         run: |
+#           chmod +x gradlew
+#           ./gradlew bootBuildImage \
+#             --imageName ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
+#       - name: OCI image vulnerability scanning
+#         uses: anchore/scan-action@v3
+#         id: scan
+#         with:
+#           image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
+#           fail-build: false
+#           severity-cutoff: high
+#       - name: Upload vulnerability report
+#         uses: github/codeql-action/upload-sarif@v2
+#         if: success() || failure()
+#         with:
+#           sarif_file: ${{ steps.scan.outputs.sarif }}
+#       - name: Log into container registry
+#         uses: docker/login-action@v2
+#         with:
+#           registry: ${{ env.REGISTRY }}
+#           username: ${{ github.actor }}
+#           password: ${{ secrets.GITHUB_TOKEN }}
+#       - name: Publish container image
+#         run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
